export const BIKE_LOAD_SUCCESS = 'BIKE_LOAD_SUCCESS';
export const BIKE_LOAD_FAILURE = 'BIKE_LOAD_FAILURE';
export const ADD_TO_CART = 'ADD_TO_CART';
export const LOG_IN_SUCCESS = 'LOG_IN_SUCCESS';
export const STAYS_LOAD_SUCCESS = 'STAY_LOAD_SUCCESS';
export const STAY_DETAILS_LOAD_SUCCESS = 'STAY_DETAILS_LOAD_SUCCESS';
export const LOCATIONS_LOAD_SUCCESS = 'LOCATIONS_LOAD_SUCCESS';
export const SELECTED_LOCATION_CHANGE = 'SELECTED_LOCATION_CHANGE';
